//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.MVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.MVVM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое время выполнения.
        /// </summary>
        public static string ActualTimePiecker {
            get {
                return ResourceManager.GetString("ActualTimePiecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая подзадача.
        /// </summary>
        public static string AddChildRadMenuItem {
            get {
                return ResourceManager.GetString("AddChildRadMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string AddRadMenuItem {
            get {
                return ResourceManager.GetString("AddRadMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации задачи.
        /// </summary>
        public static string CreatedDateLabel {
            get {
                return ResourceManager.GetString("CreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteRadMenuItem {
            get {
                return ResourceManager.GetString("DeleteRadMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о задаче.
        /// </summary>
        public static string DetailsGroupBox {
            get {
                return ResourceManager.GetString("DetailsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование задачи.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditRadMenuItem {
            get {
                return ResourceManager.GetString("EditRadMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string ExecutorsLabel {
            get {
                return ResourceManager.GetString("ExecutorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершения.
        /// </summary>
        public static string FinishedDateLabel {
            get {
                return ResourceManager.GetString("FinishedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плановая трудоёмкость задачи.
        /// </summary>
        public static string PlannedTimeLabel {
            get {
                return ResourceManager.GetString("PlannedTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое время выполнения подзадач.
        /// </summary>
        public static string SubTasksActualExecutionTimeLabel {
            get {
                return ResourceManager.GetString("SubTasksActualExecutionTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плановая трудоёмкость подзадач.
        /// </summary>
        public static string SubTasksPlannedHoursLabel {
            get {
                return ResourceManager.GetString("SubTasksPlannedHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление задачами.
        /// </summary>
        public static string TitleWindow {
            get {
                return ResourceManager.GetString("TitleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево задач.
        /// </summary>
        public static string TreeViewGroupBox {
            get {
                return ResourceManager.GetString("TreeViewGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить дерево задач.
        /// </summary>
        public static string UpdateRadMenuItem {
            get {
                return ResourceManager.GetString("UpdateRadMenuItem", resourceCulture);
            }
        }
    }
}
