//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.MVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.MVVM.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Описание&quot; обязательно для заполнения!&quot;.
        /// </summary>
        public static string DescriptionIsNull {
            get {
                return ResourceManager.GetString("DescriptionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Исполнители&quot; обязательно для заполнения!&quot;.
        /// </summary>
        public static string ExecutorsIsNull {
            get {
                return ResourceManager.GetString("ExecutorsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &quot;Дата завершения&quot; не может быть раньше Даты создания задачи!.
        /// </summary>
        public static string FinishedDateError {
            get {
                return ResourceManager.GetString("FinishedDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Плановая трудоемкость&quot; обязательно для заполнения!&quot;.
        /// </summary>
        public static string PlannedHoursIsNull {
            get {
                return ResourceManager.GetString("PlannedHoursIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус &quot;Завершена&quot; может быть присвоен только после статусов &quot;Выполняется&quot; и &quot;Приостановлена&quot;!.
        /// </summary>
        public static string StatusIsWrong {
            get {
                return ResourceManager.GetString("StatusIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена задача для сохранения.
        /// </summary>
        public static string TaskIsNull {
            get {
                return ResourceManager.GetString("TaskIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Заголовок&quot; обязательно для заполнения!.
        /// </summary>
        public static string TitleIsNull {
            get {
                return ResourceManager.GetString("TitleIsNull", resourceCulture);
            }
        }
    }
}
